name: asi-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - matplotlib
  - pip
  - kedro
  - kedro-datasets[pandas]
  - pyarrow
  - pandera
  - pyspark
  - pip:
      - pre-commit
      - ruff
      - black
      - pytest
      - wandb
      - pytest-cov
