name: asi-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - openjdk=17
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - matplotlib
  - pip
  - kedro
  - kedro-datasets[pandas]
  - pyarrow
  - pandera
  - pyspark
  - pip:
      - bokeh==3.8.0
      - autogluon==1.4.0
      - pre-commit
      - ruff
      - black
      - pytest
      - wandb
      - pytest-cov
      - fastapi
      - uvicorn
      - sqlalchemy
